version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
  groups:
    non-breaking:
      applies-to: version-updates
      update-types:
        - "minor"
        - "patch"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
