[package]
name = "cloudmqtt"
version = "0.5.0"
edition = "2021"
authors = ["Marcel Müller <neikos@neikos.email>"]
description = "A pure Rust MQTT client and server library"
readme = "README.md"
repository = "https://github.com/TheNeikos/cloudmqtt"
license = "MPL-2.0"
keywords = ["mqtt", "cloud"]
categories = ["embedded"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-timer = "3.0.3"
mqtt-format = { version = "0.5.0", path = "../mqtt-format", features = [
    "yoke",
    "mqttv5",
] }
stable_deref_trait = "1.2.0"
tokio = { version = "1.43.0", features = ["macros", "full"] }
tokio-util = { version = "0.7.12", features = ["codec", "compat"] }
tracing = "0.1.41"
typed-builder = "0.20"

futures.workspace = true
paste.workspace = true
thiserror.workspace = true
winnow = { workspace = true, default-features = true }
yoke = { workspace = true, default-features = true }
hakari = { version = "0.1", path = "../hakari" }

[dev-dependencies]
static_assertions = "1.1.0"
